### ISSUE TITLE
Search results only show what's currently visible on the map - toggle on/off

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#117]
"The thing I'd like to see most is for the location list on the left to always be in sync with the map on the right. They should always show the same locations. For example, when I search for a city, the list shows all of the pinball locations of that city. But when I zoom into specific areas in the city, I'd like the list to remove locations that are no longer in the current map view. Sort of like yelp, you know? The 'redo search when map is moved' functionality."

Maybe we could add a toggle button just above the map: "redo search when map is moved"

**Comment by RyanTG** [comment]
I'm going to start by merging the latest code into this branch. If that's a giant hassle, then I'll create a fresh branch and manually zap in your commit's code. This branch is like 1,700 commits behind.

Then I'll work on the toggle button.

**Comment by RyanTG** [comment]
Status: merge complete. Functionality there. 

Problem: Sometimes the pins don't re-drop when I shake the map around.

To do: toggle. And test more.

**Comment by RyanTG** [comment]
Possibly this for the toggle stuff. The "var" might need to be in the js application file. Or it doesn't matter. The button should only be present when loading multiple locations (unless that's a bad idea in general... we can get to that later).

##app/views/locations/_form.html.haml##
````
#mapFollow_wrapper.hide_follow_button 
  Redo results when map is moved? 
  %input{:type => "checkbox", :name => "followCheck", :id => "followCheck"}
````
````  
  var mapFollow = $('#followCheck');
````

##javascript/application##
````
  $('#followCheck').on('click',function () {
    if (mapFollow.is(':checked')) {
      if (mapAdjusted === 0) {
        google.maps.event.addListener(map, 'mouseup', function() {
          mapAdjusted = 1;
          updateMapAfterUserInteraction();
        });

        google.maps.event.addListener(map, 'zoom_changed', function() {
          mapAdjusted = 1;
          updateMapAfterUserInteraction();
        });
      }
    } 
  });
````
````
  function singleLocationLoad(region, locationID) {
    showLocationDetail(locationID);
    toggleData('show_machines_location', locationID);
    ('.hide_follow_button').addClass('hide_button');
    
    $('#show_machines_location_' + locationID).html(loadingHTML());
    $.get('/' + region + '/locations/' + locationID + '/render_machines', function(data) {
      $('#show_machines_location_' + locationID).html(data);
    });
  }
````
##css/application##
````
.hide_button {
  display: none;
}
````

**Comment by RyanTG** [comment]
Need to think about this more. This is frustrating me.

Scenario: 
1. load map results
2. move the map around
3. check the box
4. move it around again
result: If using an "IF box is checked for 'google.maps.event.addListener(map, 'mouseup', function() {' function, that value doesn't get re-checked in that function each time the box is ticked. That function has already fired, and while doing so it found the value of the checkbox. So ... I'm lost. Does the map need to reload each time the box is checked? That doesn't seem right.

**Comment by RyanTG** [comment]
@scottwainstock Is there a js concept I'm missing that can fit my needs here?

Plain English overview of the functions:
````
function checkbox() {
  // looks at the onclick on the checkbox
  if (checkbox is checked) {
   refresh results when map is moved ([this code](https://github.com/scottwainstock/pbm/blob/efcb546493e8b1db996a8e20549a9c1d0fb31024/app/assets/javascripts/application.js.erb#L91))
  }
}
````
````
function mapload() { 
  //when search button is clicked, this function runs, and the map/results load
  lotsa stuff();
  checkbox();
}
````
The checkbox() function will change when the checkbox is clicked. But mapload() only gets checkbox() when mapload() loads. Once mapload() loads, it's blind to any later changes to checkbox(). Right? If right, what's the avenue here? ajax? get/set? If I'm wrong, then I'm dumb and made a mistake.

I understand that you're busy this week and probably can't answer.

**Comment by RyanTG** [comment]
I might have to pass this back to you. I feel like it's one of those things where I don't know how to ask the question, and therefore I can't find the answer. I even posted to SO, and no one's responded.

Everything works except the new value of the checkbox isn't being passed to the redo function.

**Comment by RyanTG** [comment]
Maybe: http://stackoverflow.com/questions/15236703/val-not-getting-updated-value-from-input

.val();

**Comment by RyanTG** [comment]
Soolved that bit. The ultimate problem was that I wasn't removing the listeners.

````
function redo() {

  var listener1 = google.maps.event.addListener(map, 'mouseup', function() {
    if (!$("#followCheck").is(':checked')) {
      google.maps.event.removeListener(listener1);
    } else {
      mapAdjusted = 1;
      updateMapAfterUserInteraction();
    }
  });
  var listener2 = google.maps.event.addListener(map, 'zoom_changed', function() {
    if (!$("#followCheck").is(':checked')) {
      google.maps.event.removeListener(listener2);
    } else {
      mapAdjusted = 1;
      updateMapAfterUserInteraction();
    }
  });

}
````

There are two issues left:
- If you move the map and redo the result, and THEN you search, the map doesn't pan to the results. Note that this is an existing issue. I didn't create it with the above code.
- The little "redo" div shows up even when there's just one result. Maybe that's ok.

**Comment by RyanTG** [comment]
https://github.com/RyanTG/pbm/commit/8281026352535eeb16883e4560107aaa2ceb3083
The above issues are still unresolved. The first one is the biggest deal.

**Comment by RyanTG** [comment]
This is in an alright place. 

Main unresolved issue:
- If you drag/zoom the map, but the results are the same (e.g. if you only drag it an inch and no new locations comes into view), the map marker(s) disappear. 

Dunno the solution. Maybe more elements of the map need to reload when the map is moved.

**Comment by RyanTG** [comment]
Cool, fixed the issues! Now this seems legit.

**Comment by RyanTG** [comment]
I'll look at `rspec ./spec/features/locations_controller_spec.rb:133 # LocationsController search locations displays a location not found message instead of the ocean`

````
1) LocationsController search locations displays a location not found message instead of the ocean
     Failure/Error: expect(page).to have_content('NOT FOUND IN THIS REGION. PLEASE SEARCH AGAIN.')
       expected to find text "NOT FOUND IN THIS REGION. PLEASE SEARCH AGAIN." in "☰ Login Join portland Show Closest Locations Use two fingers to move the map Map data ©2017 Google Terms of Use Map Satellite Search: Location City Machine Type or Redo results when map is moved? Link to this Search Result"
     # ./spec/features/locations_controller_spec.rb:136:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:27:in `block (2 levels) in <top (required)>'
````

**Comment by RyanTG** [comment]
Note to self, `bounds_changed` can possibly be substituted for both `mouseup` and `zoom`. And you can add a delay: http://stackoverflow.com/a/12764689

**Comment by RyanTG** [comment]
Hmm, well, I can delay the function, and if you move twice before the delay is over, it cancels the first timer (so it doesn't fire twice). 

But it still fires multiple times. BUT, even if I move it only once, this console log will show more than one value:

````
function redo() {
  var mapupdater;
  var listener1 = google.maps.event.addListener(map, 'mouseup', function() {

      if (!$("#followCheck").is(':checked')) {
        google.maps.event.removeListener(listener1);
      } else {
        window.clearTimeout(mapupdater);
        mapupdater=window.setTimeout(function() {
          console.log(mapupdater);
          mapAdjusted = 1;
        //updateMapAfterUserInteraction();
        }, 2100);
      }

  });
  
}
````
I need to investigate this more.

**Comment by RyanTG** [comment]
Re: The "link to this search result" doesn't update to reflect the new results.

One solution would be to remove that link whenever the map is moved. Then make it come back after a new search.
