### ISSUE TITLE
Intermittent failing tests in auth_required branch

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#492]
This seems to happen after a certain hour of the day. Some weird time zone thing in date?

```
  1) LocationMachineXrefsController machine descriptions should let me add a new machine description
     Failure/Error: expect(find("#machine_condition_display_lmx_#{@lmx.id}")).to have_content("This is a new condition Updated: #{(Date.today).strftime('%d-%b-%Y')} by ssw")
       expected to find text "This is a new condition Updated: 27-Aug-2016 by ssw" in "This is a new condition Updated: 28-Aug-2016 by ssw"
     # ./spec/features/location_machine_xrefs_controller_spec.rb:225:in `block (3 levels) in <top (required)>'

  2) LocationMachineXrefsController machine descriptions displays who updated a machine if that data is available
     Failure/Error: expect(find("#machine_condition_display_lmx_#{@lmx.id}")).to have_content("Test Comment Updated: #{(Date.today).strftime('%d-%b-%Y')} by cibw")
       expected to find text "Test Comment Updated: 27-Aug-2016 by cibw" in "Test Comment Updated: 28-Aug-2016 by cibw"
     # ./spec/features/location_machine_xrefs_controller_spec.rb:235:in `block (3 levels) in <top (required)>'

Finished in 1 minute 30.73 seconds (files took 6.77 seconds to load)
49 examples, 2 failures

Failed examples:

rspec ./spec/features/location_machine_xrefs_controller_spec.rb:207 # LocationMachineXrefsController machine descriptions should let me add a new machine description
rspec ./spec/features/location_machine_xrefs_controller_spec.rb:230 # LocationMachineXrefsController machine descriptions displays who updated a machine if that data is available
```

**Comment by scottwainstock** [comment]
Fixed here: https://github.com/scottwainstock/pbm/pull/523
