### ISSUE TITLE
IFPA events not consistently added to calendar

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#645]
Admins keep noting this. I'm not sure how to troubleshoot it.

Example region: Pittsburgh. Not all their events are listed.

**Comment by scottwainstock** [comment]
```
"Adding: Mary Mac's Replay Wednesdays "
rake aborted!
JSON::ParserError: 784: unexpected token at '{"error":{"text":SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Replay Wednesdays ' order by event_end_dt' at line 1}}'
/app/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/app/vendor/bundle/ruby/2.3.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/app/lib/tasks/import_ifpa_tournaments.rake:26:in `block (2 levels) in <top (required)>'
/app/lib/tasks/import_ifpa_tournaments.rake:20:in `each'
/app/lib/tasks/import_ifpa_tournaments.rake:20:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => import_ifpa_tournaments
(See full trace by running task with --trace)
** [NewRelic][2017-04-26 03:09:26 +0000 run.* (4)] INFO : Starting Agent shutdown
```

**Comment by scottwainstock** [comment]
@RyanTG You might want to show that error to the owner of the API. It looks like they are having some kind of issue with strings that have single quotes in them? I'm basing that on the JSON::ParserError message.

I'll skip rows with this error.

**Comment by scottwainstock** [comment]
Here's a snippet from a run where I skip rows that generate a ParseError:

```
"Adding: Tucson Bi-Weekly"
"Adding: Full Tilt Ballard Weekly"
"Adding: Devil's Head EM only tournament"
"SKIPPING"
```

**Comment by scottwainstock** [comment]
This one didn't error out... looks like it's escaped.

```
"Adding: Ball Bustin\\\\\\' Bitches Women\\\\\\'s Pinball League "
```

**Comment by RyanTG** [comment]
That's a helluvan escape.

**Comment by scottwainstock** [comment]
This runs daily, so we'll see results at Apr 27 0:00 UTC.

https://github.com/scottwainstock/pbm/commit/d617d97552b5dc3c3b83e99604a5bb44c96f3184

**Comment by RyanTG** [comment]
Deprioritizing this, now that you've patched the issue.

**Comment by RyanTG** [comment]
Boatloads of new events were added this week.
